Created Information Table and Updated Rubocop
jswood23/CSCE431 pull request #24
Opened 2022-10-10 16:32 UTC by jswood23

This pull request fulfills [this user story](https://mchso-infoorganizer.atlassian.net/browse/MCHSO-15?atlOrigin=eyJpIjoiOWUxZmU2ZmU4YTFkNGM0NWI4YjMwY2IxNzUxZTE2MjMiLCJwIjoiaiJ9).
I generated a new model called `Information` that belongs to `User`. It includes a lot of the private information on each user that we want to store.
I also fixed the workflow rubocop command so that it will check more than 0 files.

2022-10-10 17:43 UTC, MengtingCao approved these changes
Looks, good. Maybe also add integration tests to check information table entry gets added when user signs up with devise and logs in with oauth?

2022-10-10 19:19 UTC, MengtingCao requested changes

2022-10-10 19:19 UTC, MengtingCao commented on app/models/information.rb
> +    info.position = 'Member'
Should we be using default position as member?

2022-10-12 20:05 UTC, ynzhang09 approved these changes
Looks good

2022-10-12 20:16 UTC, MengtingCao approved these changes

2022-10-12 20:16 UTC, merged