Nicholas contact
jswood23/CSCE431 pull request #25
Opened 2022-10-10 19:07 UTC by NR229

2022-10-10 19:12 UTC, MengtingCao approved these changes
Looks good

2022-10-10 20:55 UTC, jswood23 requested changes
Do you know what's wrong with the deployment that the image is not rendering?

2022-10-12 20:07 UTC, jswood23 requested changes

2022-10-12 20:07 UTC, jswood23 commented on app/views/external/contact.html.erb
> +            <li><a href="https://www.facebook.com/MCHSOaggies/">facebook</a></li>
Let's use `link_to` here instead of `<a>` so we can be more consistent with styling later on.

2022-10-18 13:03 UTC, closed without merging

2022-10-18 13:03 UTC, NR229 commented
Retry with different branch