Juliana home design
jswood23/CSCE431 pull request #50
Opened 2022-11-12 04:07 UTC by julianaLeano

2022-11-12 05:41 UTC, MengtingCao requested changes
“What are some components of MCH?” -typo

2022-11-12 05:42 UTC, MengtingCao requested changes
Heart Image not showing up for me

2022-11-12 17:59 UTC, jswood23 commented
Part of my PR does some basic formatting of the home page. If mine gets merged first, just overwrite whatever I made but make sure to use the correct container and box imports.

2022-11-13 04:43 UTC, jswood23 requested changes
Looks good for the most part, just one small change needed.

2022-11-13 04:43 UTC, jswood23 commented on app/assets/stylesheets/home.css
>  }
Would you please remove the `.container` code here? This is already in the `.container` portion in `containers.css`.

2022-11-13 04:59 UTC, jswood23 commented
Could you please use a sizing measurement other than `vw` or set a maximum size? The text goes outside of the box on my screen since I'm using a wide monitor. You can replicate this by setting your screen width to 3000 in chrome inspect.
![Screenshot 2022-11-12 225637](https://user-images.githubusercontent.com/56269953/201506518-c516bc1e-e001-443f-b74a-dd2ad6b4f248.png)

2022-11-13 05:13 UTC, jswood23 approved these changes
Great work! Everything looks good

2022-11-13 05:17 UTC, MengtingCao approved these changes
Looks good

2022-11-13 05:18 UTC, merged